# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SwiftDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'OptimoveSDK',:git => 'https://github.com/optimove-tech/iOS-SDK-Integration-Guide.git', :branch => 'OptimoveNotificationExtension'
end
target 'Notification Extension' do
    use_frameworks!
    pod 'OptimoveNotificationServiceExtension',:git => 'https://github.com/optimove-tech/iOS-SDK-Integration-Guide.git', :branch => 'OptimoveNotificationExtension'
end
