# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SwiftDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Firebase','~> 4.8.0'
 pod 'FirebaseMessaging', '~> 2.0.8'
 pod 'FirebaseDynamicLinks', '~> 2.3.1'
 pod 'XCGLogger', '~> 6.0.2'
 pod 'OptimovePiwikTracker'
  # Pods for swift

end
