platform :ios, '10.0'
    use_frameworks!
    pod 'Firebase'
    pod 'FirebaseMessaging'
    pod 'FirebaseDynamicLinks'
    pod 'OptimovePiwikTracker'
    target 'OptimoveSDK' do
    pod 'XCGLogger', '~> 6.0.2'

    
    target 'DevTest' do
        inherit! :search_paths
        
    end
end
