# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_modular_headers!

target 'ObjcDemoApp' do
    pod 'OptimoveSDK', '1.2.1'
end

target 'Notification Extension' do
    pod 'OptimoveNotificationServiceExtension','1.2.0'
end
