# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
use_modular_headers!

target 'ObjcDemoApp' do
  
  pod 'OptimoveSDK'

end

target 'Notification Extension' do
   
    pod 'OptimoveNotificationServiceExtension''
    
end
